# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(421, 220)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.stacked_widget = QtWidgets.QStackedWidget(self.central_widget)
        self.stacked_widget.setGeometry(QtCore.QRect(0, 0, 361, 141))
        self.stacked_widget.setObjectName("stacked_widget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.main_lbl = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(20)
        self.main_lbl.setFont(font)
        self.main_lbl.setObjectName("main_lbl")
        self.gridLayout.addWidget(self.main_lbl, 0, 0, 1, 2)
        self.encode_btn = QtWidgets.QPushButton(self.home)
        self.encode_btn.setObjectName("encode_btn")
        self.gridLayout.addWidget(self.encode_btn, 1, 0, 1, 1)
        self.decode_btn = QtWidgets.QPushButton(self.home)
        self.decode_btn.setObjectName("decode_btn")
        self.gridLayout.addWidget(self.decode_btn, 1, 1, 1, 1)
        self.stacked_widget.addWidget(self.home)
        self.encode = QtWidgets.QWidget()
        self.encode.setObjectName("encode")
        self.stacked_widget.addWidget(self.encode)
        self.decode = QtWidgets.QWidget()
        self.decode.setObjectName("decode")
        self.stacked_widget.addWidget(self.decode)
        MainWindow.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setObjectName("menubar")
        self.menu_main_menu = QtWidgets.QMenu(self.menubar)
        self.menu_main_menu.setObjectName("menu_main_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_encode = QtWidgets.QAction(MainWindow)
        self.action_encode.setObjectName("action_encode")
        self.action_decode = QtWidgets.QAction(MainWindow)
        self.action_decode.setObjectName("action_decode")
        self.menu_main_menu.addAction(self.action_encode)
        self.menu_main_menu.addAction(self.action_decode)
        self.menubar.addAction(self.menu_main_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_lbl.setText(_translate("MainWindow", "ImageSecrets"))
        self.encode_btn.setText(_translate("MainWindow", "Encode"))
        self.decode_btn.setText(_translate("MainWindow", "Decode"))
        self.menu_main_menu.setTitle(_translate("MainWindow", "main menu"))
        self.action_encode.setText(_translate("MainWindow", "encode"))
        self.action_decode.setText(_translate("MainWindow", "decode"))
