# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageSecrets(object):
    def setupUi(self, ImageSecrets):
        ImageSecrets.setObjectName("ImageSecrets")
        ImageSecrets.resize(421, 220)
        self.central_widget = QtWidgets.QWidget(ImageSecrets)
        self.central_widget.setObjectName("central_widget")
        self.stacked_widget = QtWidgets.QStackedWidget(self.central_widget)
        self.stacked_widget.setGeometry(QtCore.QRect(0, 0, 391, 141))
        self.stacked_widget.setObjectName("stacked_widget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.gridLayout = QtWidgets.QGridLayout(self.home)
        self.gridLayout.setObjectName("gridLayout")
        self.main_lbl = QtWidgets.QLabel(self.home)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(20)
        self.main_lbl.setFont(font)
        self.main_lbl.setObjectName("main_lbl")
        self.gridLayout.addWidget(self.main_lbl, 0, 0, 1, 2)
        self.encode_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.encode_btn.setFont(font)
        self.encode_btn.setObjectName("encode_btn")
        self.gridLayout.addWidget(self.encode_btn, 1, 0, 1, 1)
        self.decode_btn = QtWidgets.QPushButton(self.home)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(14)
        self.decode_btn.setFont(font)
        self.decode_btn.setObjectName("decode_btn")
        self.gridLayout.addWidget(self.decode_btn, 1, 1, 1, 1)
        self.stacked_widget.addWidget(self.home)
        self.encode = QtWidgets.QWidget()
        self.encode.setObjectName("encode")
        self.stacked_widget.addWidget(self.encode)
        self.decode = QtWidgets.QWidget()
        self.decode.setObjectName("decode")
        self.stacked_widget.addWidget(self.decode)
        ImageSecrets.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(ImageSecrets)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 421, 26))
        self.menubar.setObjectName("menubar")
        self.menu_general = QtWidgets.QMenu(self.menubar)
        self.menu_general.setObjectName("menu_general")
        ImageSecrets.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ImageSecrets)
        self.statusbar.setObjectName("statusbar")
        ImageSecrets.setStatusBar(self.statusbar)
        self.action_encode = QtWidgets.QAction(ImageSecrets)
        self.action_encode.setObjectName("action_encode")
        self.action_decode = QtWidgets.QAction(ImageSecrets)
        self.action_decode.setObjectName("action_decode")
        self.menu_general.addAction(self.action_encode)
        self.menu_general.addAction(self.action_decode)
        self.menubar.addAction(self.menu_general.menuAction())

        self.retranslateUi(ImageSecrets)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ImageSecrets)

    def retranslateUi(self, ImageSecrets):
        _translate = QtCore.QCoreApplication.translate
        ImageSecrets.setWindowTitle(_translate("ImageSecrets", "ImageSecrets"))
        self.main_lbl.setText(_translate("ImageSecrets", "ImageSecrets"))
        self.encode_btn.setText(_translate("ImageSecrets", "Encode"))
        self.decode_btn.setText(_translate("ImageSecrets", "Decode"))
        self.menu_general.setTitle(_translate("ImageSecrets", "general"))
        self.action_encode.setText(_translate("ImageSecrets", "encode"))
        self.action_decode.setText(_translate("ImageSecrets", "decode"))


__all__ = [
    "Ui_ImageSecrets",
]
